name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Cache
      uses: actions/cache@v2.1.5
      with:
        path: 
          ~/.m2/repository/
        key: maven-linux-hive
    - name: Patch for security issues
      run: |
        wget https://issues.apache.org/jira/secure/attachment/12958418/HIVE-12679.branch-2.3.patch
        patch -p0 <HIVE-12679.branch-2.3.patch
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/provectus/hive
      env:
        GITHUB_TOKEN: ${{ github.token }}
